// actionTypes.js
export const SHOW_LOGINMODAL = "SHOW_LOGINMODAL";
export const HIDE_LOGINMODAL = "HIDE_LOGINMODAL";
export const SHOW_CARTMODAL = "SHOW_CARTMODAL";
export const HIDE_CARTMODAL = "HIDE_CARTMODAL";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
export const SHOW_PRODUCT = "SHOW_PRODUCT";
export const SET_PRICE_FILTER = "SET_PRICE_FILTER";
export const SET_RATING_FILTER = "SET_RATING_FILTER";
export const SET_DISCOUNT_FILTER = "SET_DISCOUNT_FILTER";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

